config/routes.rb
Ligi::Application.routes.draw do
  

  root :to => "events#index"
  resources :events
  resources :venues
  resources :artists
  resources :users
  resources :profiles 
  resources :festivals
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/remove_saved_event/:id' => "saved_events#destroy", :as => "remove_saved_event"
  match '/add_saved_event/:id' => "saved_events#create", :as => "add_saved_event"
  
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :saved_events
  has_many :events, :through => :saved_events
  
  def owned_by(owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate, :except => [:new, :create]
  
  def show
    @profile = current_user.profile
  end
  
  def new
    @profile = Profile.new
  end
  
  def create
    @profile = Profile.new(params[:user])
    @profile.save
  end
  
  def edit
    @profile = current_user.profile
  end
  
  def update
    @profile = current_user.profile
    if @profile.update_attributes(params[:profile])
      redirect_to @profile, :notice => t('controllers.profiles.updated')
    else
      render :action => 'edit'
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_created_events.html.erb
<div id = "side_bar">
  
  <%= t('views.profiles.create_events_msg') unless @profile.user.events.any? %>

  
  <% if @profile.user.events.any? %>
    <h2><%= t('views.profiles.events_I_created') %></h2>
      <% @profile.user.events.each do |event|  %>
        <%= link_to event.artists.first.name , edit_event_path(event) %>
      <% end %>
  <% end %>
  
  <% if @profile.events.past.any? %>
    <h2><%= t('views.profiles.my_past_shows') %></h2>
      <% @profile.events.past.each do |event|  %>
        <%= link_to event.artists.first.name , edit_event_path(event) %>
      <% end %>
  <% end %>
  
</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>  <% if @profile.errors.any? %>    <div id="error_explanation">      <h2><%= t('general.there_is_an_error') %></h2>      <ul>      <% @profile.errors.full_messages.each do |msg| %>        <li><%= msg %></li>      <% end %>      </ul>    </div>  <% end %>  <div class="field">    <%= f.label t('views.profiles.name') %><br />    <%= f.text_field :name %>  </div>  <div class="actions">    <%= submit_or_cancel(f) %>  </div><% end %>

app/views/profiles/edit.html.erb
<div id="contents">
  <h1><%= t('views.profiles.edit_profile') %></h1>

  <%= render 'form' %>
</div>

app/views/profiles/show.html.erb
<%= render "created_events" %><div id="contents">  <h1>My Stuff</h1>  <i><%= t('views.profiles.no_name_set') if @profile.name.empty? %></i><%= @profile.name %> | <%= link_to t('views.profiles.change_my_profile'), edit_profile_path(@profile) %> <br \>    <%= @profile.user.email %> | <%= link_to t('views.profiles.change_my_email_pw'), edit_user_path(current_user) %> <br \>    <br \>    <%= t('views.profiles.calendar_msg') unless @profile.events.any? %>  <% if @profile.events.upcoming.any? %>    <h2> <%= t('views.profiles.my_upcoming_shows') %> </h2>    <%= render @profile.events.upcoming %>  <% end %></div>