config/routes.rb
Ligi::Application.routes.draw do
  

  root :to => "events#index"
  resources :events
  resources :venues
  resources :artists
  resources :users
  resources :profiles 
  resources :festivals
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/remove_saved_event/:id' => "saved_events#destroy", :as => "remove_saved_event"
  match '/add_saved_event/:id' => "saved_events#create", :as => "add_saved_event"
  
  

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :events
  before_create :canonicalise_name
    
  validates :name, :presence => true,
                   :uniqueness => true
  
  default_scope order('artists.name')
  scope :where_name, lambda {|term| where("artists.name LIKE ?", "%#{term}%") }
  
  
  def canonicalise_name
      require 'open-uri'
      require 'nokogiri'
      require 'htmlentities'
      coder = HTMLEntities.new
      echoKey = 'TTXOSQ9K9L1WDCRFA'
      begin
        #retrieve canonical artist name from echonest
        echonest = Nokogiri::HTML(open("http://developer.echonest.com/api/v4/artist/search?api_key=#{echoKey}&name=#{URI.escape(self.name)}&format=xml"))
        bestMatch = echonest.css('name').first
        if(bestMatch) 
            self.name = coder.decode(bestMatch.inner_html)
        end
      rescue SocketError => e
        puts "Couldn't contact EchoNest; skipping canonicalise_name."
      end
  end

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]


  # GET /artists

  def index
    @artists = Artist.where("UPPER(name) LIKE UPPER(?)", "%#{params[:q]}%")

    respond_to do |format|
      format.html # index.html.erb
	    format.json { render :json => @artists }
    end
  end

  # GET /artists/1
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    
    respond_to do |format|
      format.html #new.html.erb
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = current_user.artists.find(params[:id])
  end

  # POST /artists
  def create
    @artist = current_user.artists.new(params[:artist])
	
    respond_to do |format|
      if @artist.save
        format.html { redirect_to(new_event_path, :notice => t('controllers.artists.created')) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /artists/1
  def update
    @artist = current_user.artists.find(params[:id])
    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to(@artist, :notice => t('controllers.artists.updated')) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /artists/1
  def destroy
    @artist = current_user.artists.find(params[:id])
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to(artists_url) }
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('general.there_is_an_error') %></h2>
      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('general.artist_name') %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/artists/_popular_artists.erb
<div id = "side_bar">
  <h2><%= t('views.artists.artists_popular_today') %></h2>
  <h3>The Flaming Lips</h3>
  <h3>Arcade Fire</h3>
  <h3>This is not loaded from db yet</h3>
  <h3>Fix me!</h3>
</div>

app/views/artists/edit.html.erb
<div id="contents">
  <h1><%= t('views.artists.edit_artist') %></h1>
  <%= render 'form' %>
</div>

app/views/artists/index.html.erb
<%= render "popular_artists" %>

<div id="contents"> 

  <h1><%= t('general.all_artists') %></h1>

  <table>
    <tr>
      <th><%= t('general.artist') %></th>
      <th><%= t('views.artists.next_show') %></th>
    </tr>

  <% @artists.each do |artist| %>
    <tr>
      <td><%= link_to artist.name, artist %></td>
      <td><% event = artist.events.upcoming.first %>
            <%= link_to event.start_time.to_formatted_s(:short) + event.venue.name.to_s, event_path(event.id) unless event.nil?%><br>
    </tr>
  <% end %>
  </table>

  <br />

</div>

app/views/artists/new.html.erb
<div id="contents">
  <h1><%= t('views.artists.new_artist') %></h1>
  <%= render 'form' %>
</div>

app/views/artists/show.html.erb
<div id="contents">
  <p>
    <h1><%= @artist.name %></h1>
    <%= link_to t('general.edit'), edit_artist_path(@artist) if @artist.owned_by? current_user %>
  </p>
  <p>
    <h2><%= t('views.artists.upcoming_shows') %></h2><br />
    <i><%= t('views.artists.none') unless @artist.events.upcoming.any? %></i>
      <%= render @artist.events.upcoming %>
  </p>
  <p>
    <h2><%= t('views.artists.past_shows') %></h2><br />
    <i><%= t('views.artists.none') unless @artist.events.past.any? %></i>
    <ul>
      <% @artist.events.past %>
    </ul>
  </p>

  <% if @artist.owned_by? current_user %>
    <%= link_to t('general.edit'), edit_artist_path(@artist) %>
  <% end %>
</div>