config/routes.rb
Ligi::Application.routes.draw do
  

  root :to => "events#index"
  resources :events
  resources :venues
  resources :artists
  resources :users
  resources :profiles 
  resources :festivals
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/remove_saved_event/:id' => "saved_events#destroy", :as => "remove_saved_event"
  match '/add_saved_event/:id' => "saved_events#create", :as => "add_saved_event"
  
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  belongs_to :venue
  belongs_to :user
  belongs_to :festival
  has_and_belongs_to_many :artists
  has_many :saved_events
  has_many :profiles, :through => :saved_events
  
  attr_reader :artist_tokens
  attr_reader :venue_token
  
  validates :start_time, :venue_id, :artists, :presence => true
 
  default_scope order('events.start_time')
  scope :upcoming, lambda { where("events.start_time > ?", Time.now)}
  scope :past, lambda { where("events.start_time < ?", Time.now)}
 
 
  def artist_tokens=(ids)
    self.artist_ids = ids.split(",")
  end
  
  def venue_token=(id)
    self.venue_id = id
  end
  
  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  # GET /events
  # GET /events.xml
  def index
    @events = Event.upcoming
    @festivals = Festival.upcoming

    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.xml  { render :xml => @event }
    end
  end
  
  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      #format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = current_user.events.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = current_user.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => t('controllers.events.created')) }
        #format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        #format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = current_user.events.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => t('controllers.events.updated')) }
        #format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        #format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      #format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  # This needs to be fixed: the id variable passed works to perform the check but doesn't work to find the event. Need to investigate variable scope.
  
  def show_cost(cost)
    if cost
      if cost.nonzero?
        "#{I18n.t('views.events.cost')}: #{number_to_currency(cost)}"
      else
        t('general.free')
      end
    end
  end
  
  def add_event_shown(event)
    link_to( t('views.events.add_to_favourites'), add_saved_event_path(:id => event.id, :format => :js), :remote => true, :class => 'add_event_link')
  end
  
  def remove_event_shown(event)
    link_to(t('views.events.remove_from_favourites'), remove_saved_event_path(:id => event.id, :format => :js), :remote => true, :class => 'remove_event_link')
  end
  
  def add_event_hidden(event)
    link_to( t('views.events.add_to_favourites'), add_saved_event_path(:id => event.id, :format => :js), :remote => true, :class => 'add_event_link', :style => 'display: none;')
  end
  
  def remove_event_hidden(event)
    link_to(t('views.events.remove_from_favourites'), remove_saved_event_path(:id => event.id, :format => :js), :remote => true, :class => 'remove_event_link', :style => 'display: none;')
  end
end

app/views/events/_event.html.erb
<% div_for(event) do %>
  
  
  
  <div class="artist_date_container">
    <div class="artist_block" >
      <h2><% event.artists.each do |artist| %>  
        <%= artist.name %>  <span class='explanation'> <%= link_to t('general.more'), artist %></span><br \>
      <% end %></h2>
    </div>
    
    <div class="date_block">
      <b><%= event.start_time.strftime("%A") %></b><br />
      <%= event.start_time.strftime("%d %b") %><br />
    </div>
  </div>
  
  <div class="venue_favourites_container">
    <div class="venue_block">
      <p><h3><span class="venue_name"><%= event.venue.name unless event.venue.nil? %></b>
      <span class="explanation"> <%= link_to t('general.more'), event.venue %></span></span></h3>
      <%= show_cost(event.cost) if event.cost %><br />
    </div>
    <div class="favourites_link">
      <% if logged_in? %>
        <% if current_user.profile.events.member?(event) %>
            <%= remove_event_shown(event) %>
            <%= add_event_hidden(event) %>
        <% else %>
            <%= remove_event_hidden(event) %>
            <%= add_event_shown(event) %>
        <% end %>
      <% else %>
          <%= t('views.events.login_for_favourites') %>
      <% end%>
    </div>
  </div>
<% end %> 

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('general.there_is_an_error') %></h2>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :artist_tokens, t('views.events.artists') %><br />
    <%= f.text_field :artist_tokens, "data-pre" => @event.artists.to_json %>
	<p><%= link_to t('views.events.artist_missing'), new_artist_path %></p>
  </div>
  <div class="field">
    <%= f.label :venue_token, t('general.venue') %><br />
    <%= f.text_field :venue_token, "data-pre" => "["+@event.venue.to_json+"]" %>
	<p><%= link_to t('views.events.venue_missing'), new_venue_path %></p>
  </div>
  <div class="field">
    <%= f.label t('views.events.start_time') %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field"
    <%= f.label t('views.events.cost') %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field"
    <%= f.label t('views.events.ticket_link') %><br />
    <%= f.text_field :ticket_url %>
  </div>
  <div class="actions">
    <%= submit_or_cancel(f) %>
  </div>
<% end %>

app/views/events/_side_bar.html.erb
<div id = "side_bar">
  <h2>Upcoming Festivals</h2>
  <h3>Pop Montreal!</h3>
</div>

app/views/events/_upcoming_festivals.html.erb
<div id = "side_bar">
  <h2><%= t('views.events.upcoming_festivals') %></h2>
  <%= render @festivals %>
</div>

app/views/events/edit.html.erb
<div id="contents">
  <h1><%= t('views.events.edit_event') %></h1>

  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<%= render "upcoming_festivals" %>

<div id="contents">
  <h1><%= t('general.all_events') %></h1>
  <%= render @events %>
</div>

app/views/events/new.html.erb
<div id="contents">
  <h1><%= t('views.events.new_event') %></h1>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div id="contents">
  <% div_for(@event) do %>
    <div class="artist_date_container">
      <div class="artist_block" >
        <h2><% @event.artists.each do |artist| %>  
          <%= artist.name %> <span class='explanation'><%= link_to t('general.more'), artist %></span><br \>
        <% end %></h2>
      </div>
      
      <div class="date_block">
        <b><%= @event.start_time.strftime("%A") %></b><br />
        <%= @event.start_time.strftime("%d %b") %><br />
      </div>
    </div>
    
    <div class="venue_favourites_container">
      <div class="venue_block">
        <p><h3><span class="venue_name"><%= @event.venue.name unless @event.venue.nil? %></b>
        <span class="explanation"><%= link_to t('general.more'), @event.venue %></span></span></h3>
        <%= show_cost(@event.cost) if @event.cost %><br />
      </div>
      <div class="favourites_link">
        <% if logged_in? %>
          <% if current_user.profile.events.member?(@event) %>
              <%= remove_event_shown(@event) %>
              <%= add_event_hidden(@event) %>
          <% else %>
              <%= remove_event_hidden(@event) %>
              <%= add_event_shown(@event) %>
          <% end %>
        <% else %>
            <%= t('views.events.login_for_favourites') %>
        <% end%>
      </div>
    </div>
  <% end %>
</div>