config/routes.rb
Ligi::Application.routes.draw do
  

  root :to => "events#index"
  resources :events
  resources :venues
  resources :artists
  resources :users
  resources :profiles 
  resources :festivals
  resource :session
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/remove_saved_event/:id' => "saved_events#destroy", :as => "remove_saved_event"
  match '/add_saved_event/:id' => "saved_events#create", :as => "add_saved_event"
  
  

end

app/views/layouts/_footer.html.erb
  <div id="footer">
    <p><%= t('general.suggestions') %></p>
  </div>

app/views/layouts/_header.html.erb
<div id="header">
    <div id="logo">
      <%= image_tag("logo.png", :alt => "Live Giraffe Logo") %>
    </div>
    <div id="language_bar">
      <%= link_to "English", url_for(:locale => 'enlg') unless I18n.locale == :enlg %>
      <%= link_to "Français", url_for(:locale => 'frca') unless I18n.locale == :frca %>
    </div>
</div>

app/views/layouts/_nav_bar.html.erb
<div id="nav_bar">   <%= link_to t('general.all_events'), events_path %> |   <%= link_to t('general.all_venues'), venues_path %> |  <%= link_to t('general.all_artists'), artists_path %> |  <% if logged_in? %>    <%= link_to t('general.add_something'), new_event_path %> |    <%= link_to t('general.my_stuff'), current_user.profile  %> |    <%= link_to t('general.logout'), logout_path %> |  <% else %>    (<%= link_to t('general.login'), login_path %>    <%= t('general.or') %>    <%= link_to t('general.register'), new_user_path %>     <%= t('general.to_add_or_edit_content')%>)  <% end %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('general.live_giraffe') %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
  
</head>
<body>
<div id="container">
  <%= render "layouts/header" %>
  <%= render "layouts/nav_bar" %>
  <%= content_tag :p, notice, :class => 'notice' if notice.present? %>
  <%= content_tag :p, alert, :class => 'alert' if alert.present? %>
  <%= yield %>
  <%= render "layouts/footer" %>
</div>

</body>
</html>